# Generated by Django 3.2 on 2022-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_price', models.FloatField()),
                ('anchor', models.IntegerField()),
                ('extra_price', models.FloatField()),
                ('price_percent', models.FloatField()),
                ('price_protect', models.FloatField()),
            ],
        ),
    ]
