# Generated by Django 3.2 on 2022-11-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='price',
            table='Price',
        ),
    ]
