# Generated by Django 3.2 on 2022-11-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountApi', '0001_initial'),
        ('BaseApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AccountApi.account')),
                ('name', models.CharField(default='User', max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female')], default=0)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('url_identification_top', models.CharField(max_length=255, null=True)),
                ('url_identification_back', models.CharField(max_length=255, null=True)),
                ('identification_info', models.CharField(blank=True, max_length=500, null=True)),
                ('url_face_video', models.CharField(max_length=255, null=True)),
                ('confirmed', models.IntegerField(choices=[(0, 'UnConfirm'), (1, 'Confirming'), (2, 'Confirmed'), (-1, 'Deny')], default=0)),
                ('distance_receive', models.IntegerField(default=10)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseApi.address')),
            ],
            options={
                'db_table': 'Shipper',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AccountApi.account')),
                ('name', models.CharField(default='User', max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female')], default=0)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_view', models.IntegerField(default=10)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='BaseApi.address')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
