# Generated by Django 3.2 on 2022-11-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipper',
            old_name='latitude',
            new_name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='longitude',
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
