# Generated by Django 3.2 on 2022-11-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0002_auto_20221127_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='identification_info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
