# Generated by Django 3.2 on 2022-11-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApi', '0001_initial'),
        ('UserApi', '0003_alter_shipper_identification_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AccountApi.account')),
                ('name', models.CharField(default='Admin', max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female')], default=0)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
    ]
