# Generated by Django 3.2 on 2022-12-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='avatar_url',
            field=models.CharField(blank=True, default='/static/admin/img/logo/go_ship.png', max_length=255, null=True),
        ),
    ]
