# Generated by Django 3.2 on 2022-12-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0006_alter_customer_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar_url',
            field=models.CharField(blank=True, default='/static/admin/img/logo/user.png', max_length=255, null=True),
        ),
    ]
