# Generated by Django 3.2 on 2022-12-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0008_auto_20221202_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='home_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
