# Generated by Django 3.2 on 2022-12-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Có đơn hàng gần đây'), (2, 'Tài xế đã nhận đơn hàng')], null=True)),
            ],
        ),
    ]
