# Generated by Django 3.2 on 2022-12-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApi', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Có đơn hàng gần đây'), (2, 'Tài xế đã nhận đơn hàng'), (3, 'Đơn hàng của bạn đang được vận chuyển')], null=True),
        ),
    ]
