# Generated by Django 3.2 on 2022-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApi', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Có đơn hàng gần đây'), (2, 'Tài xế đã nhận đơn hàng'), (3, 'Đơn hàng của bạn đang được vận chuyển'), (5, 'Vui lòng xác nhận hoàn thành đơn hàng'), (6, 'Hoàn thành đơn hàng')], null=True),
        ),
    ]
