# Generated by Django 3.2 on 2022-11-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApi', '0001_initial'),
        ('BaseApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('is_protected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.BigIntegerField(null=True)),
                ('distance', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('customer_notes', models.TextField(blank=True, max_length=255, null=True)),
                ('address_end', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_end', to='BaseApi.address')),
                ('address_start', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_start', to='BaseApi.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderApi.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApi.customer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderApi.payment')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApi.shipper')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderApi.status')),
            ],
        ),
    ]
