# Generated by Django 3.2 on 2022-11-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApi', '0002_auto_20221123_0012'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='Payment',
        ),
        migrations.AlterModelTable(
            name='status',
            table='Status',
        ),
    ]
