# Generated by Django 3.2 on 2022-11-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApi', '0004_alter_status_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='img_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
