# Generated by Django 3.2 on 2022-12-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApi', '0006_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rating',
            field=models.BooleanField(default=False),
        ),
    ]
