# Generated by Django 3.2 on 2022-12-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApi', '0007_order_is_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, max_length=1000, null=True)),
                ('rate', models.IntegerField(choices=[(1, '1*'), (2, '2*'), (3, '3*'), (4, '4*'), (5, '5*')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderApi.order')),
            ],
        ),
    ]