# Generated by Django 3.2 on 2022-12-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApi', '0008_alter_rate_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_order', to='OrderApi.order'),
        ),
        migrations.AlterModelTable(
            name='rate',
            table='Rate',
        ),
    ]
