# Generated by Django 3.2 on 2022-12-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApi', '0009_auto_20221217_2143'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
