# Generated by Django 3.2 on 2022-12-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApi', '0009_auto_20221217_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_order', to='OrderApi.rate'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
