# Generated by Django 3.2 on 2022-12-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApi', '0010_alter_order_table'),
        ('OrderApi', '0010_auto_20221225_2330'),
    ]

    operations = [
    ]
